"""
Script to analyze results from untitled0/2/6.py and compute ratings.

@author: wrotki8778
"""
import os
import pandas as pd
import numpy as np
import numexpr as ne
import math
os.chdir('C:/Users/kubaf/Documents/Skoki')


def merge_stats(directory):
    """
    Merge all dataframes containing get_round outputs.

    See untitled2.py file for reference.

    Parameters
    ----------
    directory : string
        Directory with all files generated by get_round procedure.

    Returns
    -------
    stats : pandas dataframe
        Dataframe with merged statistics files. The form of dataframe
        does not change.
    """
    columns_names = ['fis_code', 'humid', 'snow',
                     'air', 'weather_type', 'round_type', 'max_wind',
                     'avg_wind', 'min_wind', 'gate', 'counted_jumpers',
                     'all_jumpers', 'all_countries']
    stats = pd.DataFrame([], columns=columns_names)
    list_of_files = os.listdir(directory)
    for item in list_of_files:
        tmp = pd.read_csv(directory+'\\'+item, sep=',')
        stats = stats.append(tmp)
    stats = stats.drop_duplicates(['fis_code', 'round_type'])
    stats[['humid', 'snow', 'air', 'max_wind',
           'avg_wind', 'min_wind', 'gate', 'counted_jumpers',
           'all_jumpers', 'all_countries']] =\
        stats[['humid', 'snow', 'air', 'max_wind',
               'avg_wind', 'min_wind', 'gate', 'counted_jumpers',
               'all_jumpers', 'all_countries']].apply(pd.to_numeric)
    return stats


def merge_infos(directory):
    """
    Merge all files which contain outputs from untitled6.py module.

    (competitions dataframe).

    Parameters
    ----------
    directory : string
        Directory with all files generated by untitled6.py module.

    Returns
    -------
    comps : pandas dataframe
        Dataframe with merged competition information files.
        The form of dataframe does not change.

    """
    columns_names = ['codex', 'place', 'gender', 'hill_size_x',
                     'team', 'season', 'hill_size_y', 'k-point',
                     'meter value', 'gate factor', 'wind factor',
                     'type', 'date', 'id', 'training']
    comps = pd.DataFrame([], columns=columns_names)
    list_of_files = os.listdir(directory)
    for item in list_of_files:
        tmp = pd.read_csv(directory+'\\'+item, sep=',')
        country = [x.rsplit(' ', 1)[1][1:4] for x in tmp['place']]
        new_place = [x.rsplit(' ', 1)[0] for x in tmp['place']]
        tmp['place'] = pd.DataFrame(new_place)
        tmp['country'] = pd.DataFrame(country)
        comps = comps.append(tmp)
    comps = comps.drop_duplicates(['id'])
    comps[['hill_size_x', 'team', 'season', 'hill_size_y', 'k-point',
           'meter value', 'gate factor', 'wind factor', 'type', 'training']] =\
        comps[['hill_size_x', 'team',
               'season', 'hill_size_y', 'k-point',
               'meter value', 'gate factor',
               'wind factor', 'type', 'training']].apply(pd.to_numeric)
    return comps


def new_rating(ratings, k):
    """
    Compute deltas to update ratings.

    Parameters
    ----------
    ratings : vector of floats
        Ordered vector of initial ratings (before computing deltas).
    k : float
        Magnitude of rating change (bigger k <-> bigger changes).

    Returns
    -------
    delty : vector of floats
        Ordered vector of changes in initial ratings.

    """
    delty = np.array(ratings)
    n = len(delty)
    delty_matrix = np.tile(delty, (n, 1))
    delty_matrix = (delty_matrix - delty_matrix.T)/400
    results = ne.evaluate('1/(10**delty_matrix + 1)')
    exp_score = np.sum(results, axis=1, initial = -0.5)
    fact_score = np.flip(np.arange(n))
    return k*(fact_score - exp_score)/10

def append_rating(results, comp, rating_db, k, round_name):
    """
    Update ratings in a incremental way.

    Parameters
    ----------
    results : Pandas dataframe
        Dataframe with the results of the given competition round.
    i : integer
        Variable counting the number of competitions before a given round
    comps : Pandas dataframe
        Infos about all competitions gathered in a way provided by import_links
        function in untitled6.py script (check "database" output for details).
    rating_act : Pandas dataframe
        Dataframe containing all deltas until a given competition round.
    rating_db : Pandas dataframe
        Dataframe containing aggregated deltas until a given competition round.
    k : float
        Magnitude of rating change (bigger k <-> bigger changes).
    round_name : string
        Name of round for which the rating is updated.

    Returns
    -------
    list
        new_rating_act : Pandas dataframe
            Dataframe containing all deltas after a given competition round.
        new_rating_db : Pandas dataframe
            Dataframe containing aggregated deltas
            after a given competition round.

    """
    ratings = results['cumm_rating']
    results['delty'] = new_rating(ratings, 8)
    results['id'] = comp.name
    results['round'] = round_name
    #results['short_rating'] = short_rating_compute(i, results, comps,
    #                                               rating_act)
    new_rating_db = pd.merge(rating_db, results[['codex', 'delty']],
                             on='codex', how='left')
    new_rating_db['cumm_rating'] = new_rating_db['cumm_rating']\
        + new_rating_db.fillna(0)['delty']*(1 - comp['training'])*(k/8)
    new_rating_db = new_rating_db.drop(['delty'], axis=1)
    return [results, new_rating_db]


def neighborhood_comps(comps,code):
    comp = comps[comps['id'] == code]
    comp_number = comp.index.item()
    codes = comps.loc[comp_number-12:comp_number]
    filtered_codes = codes[codes['place'] == comp.iloc[0]['place']]['id']
    return(list(filtered_codes))


def short_rating_compute(i, results, comps, rating_act):
    if comps.loc[i]['training']:
        return 0
    correct_ids = neighborhood_comps(comps, comps.loc[i]['id'])
    if not correct_ids:
        return 0
    rating_tmp = rating_act[rating_act['id'].isin(correct_ids)][['codex',
                                                                 'delty']]
    rating_tmp = rating_tmp.groupby('codex').mean(['delty'])
    results = pd.merge(results, rating_tmp, how='left', on='codex')
    return results['delty_y'].fillna(0)


def initialize_build_rating(names):
    rating_db = pd.DataFrame(names['codex'])
    rating_db = rating_db.drop_duplicates()
    rating_db.dropna()
    rating_db['cumm_rating'] = 1000
    return rating_db


def build_rating(comp, names, results=pd.DataFrame(),
                 rating_db=pd.DataFrame(), round_name=False):
    """
    Create a dataframe with ratings of all athletes.

    Ratings indicate their level over time.

    Parameters
    ----------
    comp : Pandas dataframe
        Series with the information about the competition.
    results : Pandas dataframe
        Dataframe with the results of given competition round.
    names : Pandas dataframe
        Dataframe with one-to-many map connecting every athlete with his/hers
        FIS code.

    Returns
    -------
    rating_act : Pandas dataframe
        Dataframe containing deltas (increments) of rating of every athlete
        after all competition rounds.
    rating_db : Pandas dataframe
        Dataframe containing aggregated deltas of every athlete
        after all competition rounds.

    """
    if rating_db.empty:
        rating_db = initialize_build_rating(names)
    k = 8 * (1 + max(2013 - comp['season'], 0))
    # print(k)
    # print(comp)
    # print(round_name)
    if results.empty:
        if comp['training'] == 1:
            # print('omitted')
            return pd.DataFrame(), rating_db
        file_name = os.getcwd()+'\\nazwy\\'+comp.name[:10]+'nazfis.csv'
        if os.path.exists(file_name):
            results = pd.read_csv(file_name, sep=';', header=None)
            if comp['team']:
                return pd.DataFrame(), rating_db
            results.columns = ['bib', 'codex', 'name']
            results = results.drop(['bib','name'], axis=1)
            # results['round'] = 'whole competition '
            # results['points'] = 1
            # results['dist_points'] = 1
            # results['dist'] = 1
            # print('imported from nazfis.csv file')
            round_name = 'whole competition '
            k = 2*k
        else:
            return pd.DataFrame(), rating_db
    new_results = pd.merge(results, rating_db, how='left', on='codex')
    new_rating_act, new_rating_db = append_rating(new_results, comp,
                                                  rating_db, k, round_name)
    return new_rating_act, new_rating_db


actual_comps = merge_infos(os.getcwd()+'\\comps\\')
actual_comps.to_csv(os.getcwd()+'\\all_comps.csv', index=False, na_rep='NA')
actual_stats = merge_stats(os.getcwd()+'\\stats\\')
actual_stats.to_csv(os.getcwd()+'\\all_stats.csv', index=False, na_rep='NA')
actual_stats_rounds = {_: list(x['round_type'])
                       for _, x in actual_stats.groupby(['fis_code'])}
# here execute skrypt2.R
# actual_comps = actual_comps[actual_comps['training'] == 0]
actual_comps = actual_comps[actual_comps['season'] > 2009]
actual_comps = actual_comps.sort_values(['date', 'id'],
                                        ascending=[True, False])
actual_comps = actual_comps.set_index(['id'])
actual_names = pd.read_csv(os.getcwd()+'\\all_names.csv')
actual_results = pd.read_csv(os.getcwd()+'\\all_results.csv')
actual_results_split = {_: x.sort_values(by=['points', 'dist_points', 'loc'],
                                         ascending=[False, False, True])['codex'].dropna()
                        for _, x in actual_results.groupby(['id', 'round'])}

rating_db = pd.DataFrame()
rating_act = pd.DataFrame()
rating_results = {}
for primary_id in list(actual_comps.index):
    if primary_id in actual_stats_rounds.keys():
        round_names = actual_stats_rounds[primary_id]
    else:
        continue
    comp = actual_comps.loc[primary_id]
    for round_name in round_names:
        if (primary_id, round_name) in actual_results_split.keys():
            results = actual_results_split[(primary_id, round_name)]
        else:
            results = pd.DataFrame()
        rating_act, rating_db = build_rating(comp, actual_names, results,
                                             rating_db=rating_db,
                                             round_name=round_name)
        rating_results[(primary_id, round_name)] = rating_act
rating_final = pd.DataFrame().append(list(rating_results.values()))
# Execution time 4x reduced (280s -> 70s)
rating_final.to_csv(os.getcwd()+'\\all_ratings.csv',
                        index=False, na_rep='NA')


